version: '3'
services:

  sql_db:
    image: grochu25/sql-turnieje-projekt
    container_name: sql_db
    ports:
      - 3306:3306
    networks:
      - spring-network

  spring_app:
    image: grochu25/spring-turnieje-projekt
    container_name: spring_app
    ports:
      - 8080:8080
    networks:
      - spring-network
    links:
      - sql_db

networks:
  spring-network: {}